Models/Customer/CustomerLogin.cs
namespace AD2_WEB_APP.Models.Customer;

using System.ComponentModel.DataAnnotations;

public class CustomerLogin
{

    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }

}

Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections;
using System.Text.Json;
namespace AD2_WEB_APP.Pages;

public class CartModel : PageModel
{
    private readonly ILogger<CartModel> _logger;

    public ArrayList cartList;
    public Int32 amount;
    public CartModel(ILogger<CartModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        amount=0;
        ArrayList myAL = new ArrayList();
        for (int i = 1; i < 55; i++)
        {
           
            var id = HttpContext.Session.GetInt32("id" + i);
            var price = HttpContext.Session.GetInt32("price" + i);
            if (id != null && price != null)
            {
                amount=(amount + Convert.ToInt32(price));
                // myAL.Add(id);
                
                myAL.Add(price);
            }

        }
        if (myAL != null)
        {
            cartList = myAL;
            var json2 = JsonSerializer.Serialize(cartList);
            //System.Console.Write(json2);
        }

    }
}

Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AD2_WEB_APP.Pages;

public class CheckoutModel : PageModel
{
    private readonly ILogger<CheckoutModel> _logger;
    public Int32 amount;
    public CheckoutModel(ILogger<CheckoutModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
     
        for (int i = 1; i < 55; i++)
        {
           
            var id = HttpContext.Session.GetInt32("id" + i);
            var price = HttpContext.Session.GetInt32("price" + i);
            if (id != null && price != null)
            {
                amount=(amount + Convert.ToInt32(price));
              
            }

        }
       
    }
}

Pages/CustomerLogin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AD2_WEB_APP.Models.Customer;
using AD2_WEB_APP.Services;


namespace AD2_WEB_APP.Pages;

public class CustomerLoginModel : PageModel
{
    private readonly ILogger<CustomerLoginModel> _logger;

    [BindProperty]
    public CustomerLogin Model { get; set; }
    private ICustomerService _customerService;

    public CustomerLoginModel(ILogger<CustomerLoginModel> logger, ICustomerService customerService)
    {
        _logger = logger;
    }

    [TempData]
    public string Message { get; set; }

    [TempData]
    public string Type { get; set; }


    public void OnGet()
    {

    }

    public async Task<IActionResult> OnPostAsync()
    {
        try
        {
            var data = Model;

            string token = _customerService.Authenticate(data);
           
            Type = "success";
            Message = "Customer created !";
            return Page();
        }
        catch (System.Exception e)
        {

            Type = "error";
            Message = e.Message;
            return Page();
        }


    }
}

Pages/CustomerRegister.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AD2_WEB_APP.Models.Customer;
using AD2_WEB_APP.Services;

namespace AD2_WEB_APP.Pages;

public class CustomerRegisterModel : PageModel
{
    private readonly ILogger<CustomerRegisterModel> _logger;

    [BindProperty]
    public CreateRequestCustomer Model { get; set; }

    private ICustomerService _customerService;

    public CustomerRegisterModel(ILogger<CustomerRegisterModel> logger, ICustomerService customerService)
    {
        _logger = logger;
        _customerService = customerService;
    }

    [TempData]
    public string Message { get; set; }

    [TempData]
    public string Type { get; set; }

    public void OnGet()
    {

    }

    public IActionResult OnPost()
    {
        try
        {
            var data = Model;

            _customerService.Create(data);
            Type = "success";
            Message = "Customer created !";
            return Page();
        }
        catch (System.Exception e)
        {

            Type = "error";
            Message = e.Message;
            return Page();
        }


    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AD2_WEB_APP.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AD2_WEB_APP.Services;
using AD2_WEB_APP.Models.ComputerModel;
using Microsoft.AspNetCore.Http;
namespace AD2_WEB_APP.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private IComputerModelService _computerService;
    public IndexModel(ILogger<IndexModel> logger, IComputerModelService computerService)
    {
        _logger = logger;
        _computerService = computerService;
    }
    public List<GetRequestComputerModel> itemList { get; set; }
    public void OnGet()
    {

        itemList = _computerService.GetAll();
    }


    public void OnPostSetItem(int id,int price)
    {
        try
        {
            itemList = _computerService.GetAll();
            HttpContext.Session.SetInt32("id" + id, id);
            HttpContext.Session.SetInt32("price" + id, price);
        }
        catch (System.Exception)
        {

            throw;
        }

    }

}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AD2_WEB_APP.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


Pages/Shop.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AD2_WEB_APP.Services;
using AD2_WEB_APP.Models.ComputerModel;

namespace AD2_WEB_APP.Pages;

public class ShopModel : PageModel
{
    private readonly ILogger<ShopModel> _logger;
    private IComputerModelService _computerService;
    public ShopModel(ILogger<ShopModel> logger,IComputerModelService computerService)
    {
        _logger = logger;
        _computerService = computerService;
    }
    public List<GetRequestComputerModel> itemList { get; set; }
    public void OnGet()
    {
        itemList = _computerService.GetAll();
    }

    public void OnPostSetItem(int id,int price)
    {
        try
        {
            itemList = _computerService.GetAll();
            HttpContext.Session.SetInt32("id" + id, id);
            HttpContext.Session.SetInt32("price" + id, price);
        }
        catch (System.Exception)
        {

            throw;
        }

    }
}

Pages/Single-product.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AD2_WEB_APP.Services;
using AD2_WEB_APP.Entities;
using AD2_WEB_APP.Models.ComputerModel;

namespace AD2_WEB_APP.Pages;

public class SigleProductModel : PageModel
{
    [BindProperty(Name = "id", SupportsGet = true)]
    public int Id { get; set; }
    private readonly ILogger<SigleProductModel> _logger;
    private IComputerModelService _computerService;
     public GetRequestComputerModel item { get; set; }

    public SigleProductModel(ILogger<SigleProductModel> logger,
    IComputerModelService computerService)
    {
        _logger = logger;
        _computerService = computerService;
    }

    public void OnGet()
    {
        if (Id==null)
        {
            item = _computerService.GetComputerById(1);
        }else
        {
            item = _computerService.GetComputerById(Id);
        }
        
    }
}

Pages/CustomerLogin.cshtml
@page
@model CustomerLoginModel
@{
    ViewData["Title"] = "Login Register";
}

<div class="container mt-20">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email
                        Address</label>
                    <input type="text" asp-for="Model.Email"
                        class="form-control" required />
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password"
                        class="form-control" required/>
                    <span asp-validation-for="Model.Password"
                        class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

Pages/CustomerRegister.cshtml
@page
@model CustomerRegisterModel
@{
    ViewData["Title"] = "Customer Register";
}

<div class="container mt-20">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <br/>
            <br/>
            <br/>
            <h1 class="mb-3">Register</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.FirstName">FirstName</label>
                    <input type="text" asp-for="Model.FirstName" class="form-control" required />
                    <span asp-validation-for="Model.FirstName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.LastName">LastName</label>
                    <input type="text" asp-for="Model.LastName" class="form-control" required />
                    <span asp-validation-for="Model.LastName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email Address</label>
                    <input type="text" asp-for="Model.Email" class="form-control" required />
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control" required/>
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Phone_Number">Phone Number</label>
                    <input type="text" asp-for="Model.Phone_Number" class="form-control" required />
                    <span asp-validation-for="Model.Phone_Number" class="text-danger"></span>
                </div>
                <hr/>
                 <br/>
                 <br/>
                <h4 class="form-label" style="opacity:0.5;">Billing</h4>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Street_Address_billing">Street Address</label>
                    <input type="text" asp-for="Model.Street_Address_billing" class="form-control" required />
                    <span asp-validation-for="Model.Street_Address_billing" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.City_billing">City</label>
                    <input type="text" asp-for="Model.City_billing" class="form-control" required />
                    <span asp-validation-for="Model.City_billing" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.State_billing">State</label>
                    <input type="text" asp-for="Model.State_billing" class="form-control" required />
                    <span asp-validation-for="Model.State_billing" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Zip_Code_billing">Zip Code</label>
                    <input type="text" asp-for="Model.Zip_Code_billing" class="form-control" required />
                    <span asp-validation-for="Model.Zip_Code_billing" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Country_billing">Country</label>
                    <input type="text" asp-for="Model.Country_billing" class="form-control" required />
                    <span asp-validation-for="Model.Country_billing" class="text-danger"></span>
                </div>

                 <hr/>
                <h4 class="form-label" style="opacity:0.5;">Shipping</h4>
                <br/>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Street_Address_shipping">Street Address</label>
                    <input type="text" asp-for="Model.Street_Address_shipping" class="form-control" required />
                    <span asp-validation-for="Model.Street_Address_shipping" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.City_shipping">City</label>
                    <input type="text" asp-for="Model.City_shipping" class="form-control" required />
                    <span asp-validation-for="Model.City_shipping" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.State_shipping">State</label>
                    <input type="text" asp-for="Model.State_shipping" class="form-control" required />
                    <span asp-validation-for="Model.State_shipping" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Zip_Code_shipping">Zip Code</label>
                    <input type="text" asp-for="Model.Zip_Code_shipping" class="form-control" required />
                    <span asp-validation-for="Model.Zip_Code_shipping" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                    <label class="form-label" asp-for="Model.Country_shipping">Country</label>
                    <input type="text" asp-for="Model.Country_shipping" class="form-control" required />
                    <span asp-validation-for="Model.Country_shipping" class="text-danger"></span>
                </div>
                 <br/>
                 
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
                <br/>
                <br/>
                <br/>
            </form>
        </div>
    </div>
</div>

Pages/Shop.cshtml
@page
@model ShopModel
@{
    ViewData["Title"] = "Shop Page";
}

    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                      <div class="logo">
                        <h1><a href="./"><img src="~/home/img/logo-new.jpg"
                        width="50" height="50"></a></h1>
                    </div>
                </div>
                
                <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="cart.html">Cart - <span class="cart-amunt">$100</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">5</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->
    
    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> 
                <div class="navbar-collapse collapse">
                       <ul class="nav navbar-nav">
                        <li><a href="/Index">Home</a></li>
                        <li  class="active"><a href="/Shop">Shop page</a></li>
                        
                        <li><a href="/Cart">Cart</a></li>
                        <li><a href="/Checkout">Checkout</a></li>
                        <li><a href="#">Category</a></li>
                        <li><a href="#">Others</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>  
            </div>
        </div>
    </div> <!-- End mainmenu area -->
    
    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Shop</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                @foreach (var item in Model.itemList){
             
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <div class="product-upper">
                           <img src="~/images/@item.ImagePath" alt="">
                        </div>
                        <h2><a  asp-page="single-product" asp-route-id="@item.Id">@item.Model_Name</a></h2>
                        <div class="product-carousel-price">
                            <ins>LKR @item.Configuration[0].Price.00</ins> <del>LKR @item.Configuration[0].ComparePrice.00</del>
                        </div>  
                        
                        <div class="product-option-shop">
                                         <form asp-page-handler="SetItem" method="post">
                                            
                                          <button class="btn btn-default"><a class="add_to_cart_button btn btn-default" type="button"
                                        ><i class="fa fa-shopping-cart"></i>  Add to cart</a></button>
                                             <input type="hidden" name="id" value="@item.Id" />
                                              <input type="hidden" name="price" value="@item.Configuration[0].Price" />
                                         </form>
                           
                        </div>                       
                    </div>
                </div>

                }
                
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    <div class="product-pagination text-center">
                        <nav>
                          <ul class="pagination">
                            <li>
                              <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                              </a>
                            </li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li>
                              <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                              </a>
                            </li>
                          </ul>
                        </nav>                        
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>u<span>Stora</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="">My account</a></li>
                            <li><a href="">Order history</a></li>
                            <li><a href="">Wishlist</a></li>
                            <li><a href="">Vendor contact</a></li>
                            <li><a href="">Front page</a></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="">Mobile Phone</a></li>
                            <li><a href="">Home accesseries</a></li>
                            <li><a href="">LED TV</a></li>
                            <li><a href="">Computer</a></li>
                            <li><a href="">Gadets</a></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <input type="email" placeholder="Type your email">
                            <input type="submit" value="Subscribe">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                       <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
   